import { RSSSource } from './types';

export const mediaSources: RSSSource[] = [
  // Official RSS
  {
    name: '人民网传媒',
    url: 'http://www.people.com.cn/rss/media.xml',
    icon: '🏛️',
    category: 'chinese',
  },
  {
    name: '人民网时政',
    url: 'http://www.people.com.cn/rss/politics.xml',
    icon: '🏛️',
    category: 'chinese',
  },
  {
    name: '新华网国内',
    url: 'http://rss.xinhuanet.com/rss/native.xml',
    icon: '📡',
    category: 'chinese',
  },
  {
    name: '新华网国际',
    url: 'http://rss.xinhuanet.com/rss/world.xml',
    icon: '📡',
    category: 'chinese',
  },
  {
    name: '新华网财经',
    url: 'http://rss.xinhuanet.com/rss/fortune.xml',
    icon: '📡',
    category: 'chinese',
  },
  {
    name: '新华网证券',
    url: 'http://rss.xinhuanet.com/rss/stock.xml',
    icon: '📡',
    category: 'chinese',
  },
  // RSSHub routes
  {
    name: '央视新闻',
    url: 'https://rsshub.app/cctv/news',
    icon: '📺',
    category: 'chinese',
  },
  {
    name: '央视国内',
    url: 'https://rsshub.app/cctv/china',
    icon: '📺',
    category: 'chinese',
  },
  {
    name: '央视国际',
    url: 'https://rsshub.app/cctv/world',
    icon: '📺',
    category: 'chinese',
  },
  {
    name: '央视科技',
    url: 'https://rsshub.app/cctv/tech',
    icon: '📺',
    category: 'chinese',
  },
  {
    name: '羊城晚报要闻',
    url: 'https://rsshub.app/ycwb/22',
    icon: '📰',
    category: 'chinese',
  },
  {
    name: '羊城晚报广州',
    url: 'https://rsshub.app/ycwb/18',
    icon: '📰',
    category: 'chinese',
  },
  {
    name: '羊城晚报广东政经',
    url: 'https://rsshub.app/ycwb/13074',
    icon: '📰',
    category: 'chinese',
  },
  {
    name: '证券时报要闻',
    url: 'https://rsshub.app/stcn/article/list/yw',
    icon: '💹',
    category: 'chinese',
  },
  {
    name: '证券时报股市',
    url: 'https://rsshub.app/stcn/article/list/gs',
    icon: '💹',
    category: 'chinese',
  },
  {
    name: '证券时报公司',
    url: 'https://rsshub.app/stcn/article/list/company',
    icon: '💹',
    category: 'chinese',
  },
  {
    name: '证券时报金融',
    url: 'https://rsshub.app/stcn/article/list/finance',
    icon: '💹',
    category: 'chinese',
  },
  // SZSE stock announcements
  {
    name: '粤传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=002181',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '华媒控股',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000607',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '中原传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000719',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '华数传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000156',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '新媒股份',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=300770',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '海看股份',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=301262',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '电广传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000917',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '天威视讯',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=002238',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '湖北广电',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000665',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '分众传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=002027',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '兆讯传媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=301102',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '省广集团',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=002400',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '芒果超媒',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=300413',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '蓝色光标',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=300058',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '利欧股份',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=002131',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '智度股份',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=000676',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '每日互动',
    url: 'https://rsshub.app/szse/disclosure/listed/notice/stock=300766',
    icon: '📋',
    category: 'chinese',
  },
  // SSE stock announcements
  {
    name: '浙数文化',
    url: 'https://rsshub.app/sse/disclosure/productId=600633',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '新华传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=600825',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '博瑞传播',
    url: 'https://rsshub.app/sse/disclosure/productId=600880',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '中文传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=600373',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '读者传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=603999',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '东方明珠',
    url: 'https://rsshub.app/sse/disclosure/productId=600637',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '江苏有线',
    url: 'https://rsshub.app/sse/disclosure/productId=600959',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '歌华有线',
    url: 'https://rsshub.app/sse/disclosure/productId=600037',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '吉视传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=601929',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '北巴传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=600386',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '人民网',
    url: 'https://rsshub.app/sse/disclosure/productId=603000',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '新华网',
    url: 'https://rsshub.app/sse/disclosure/productId=603888',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '浙文互联',
    url: 'https://rsshub.app/sse/disclosure/productId=600986',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '三人行',
    url: 'https://rsshub.app/sse/disclosure/productId=605168',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '引力传媒',
    url: 'https://rsshub.app/sse/disclosure/productId=603598',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '天下秀',
    url: 'https://rsshub.app/sse/disclosure/productId=600556',
    icon: '📋',
    category: 'chinese',
  },
  {
    name: '龙韵股份',
    url: 'https://rsshub.app/sse/disclosure/productId=603729',
    icon: '📋',
    category: 'chinese',
  },
];
